package com.itheima.ssm.entity;

public class SCust {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.cust_name
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.cust_type
     *
     * @mbggenerated
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.cust_phone
     *
     * @mbggenerated
     */
    private String custPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.cust_address
     *
     * @mbggenerated
     */
    private String custAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_cust.cust_link_user
     *
     * @mbggenerated
     */
    private Integer custLinkUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.cid
     *
     * @return the value of s_cust.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.cid
     *
     * @param cid the value for s_cust.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.cust_name
     *
     * @return the value of s_cust.cust_name
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.cust_name
     *
     * @param custName the value for s_cust.cust_name
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.cust_type
     *
     * @return the value of s_cust.cust_type
     *
     * @mbggenerated
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.cust_type
     *
     * @param custType the value for s_cust.cust_type
     *
     * @mbggenerated
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.cust_phone
     *
     * @return the value of s_cust.cust_phone
     *
     * @mbggenerated
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.cust_phone
     *
     * @param custPhone the value for s_cust.cust_phone
     *
     * @mbggenerated
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.cust_address
     *
     * @return the value of s_cust.cust_address
     *
     * @mbggenerated
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.cust_address
     *
     * @param custAddress the value for s_cust.cust_address
     *
     * @mbggenerated
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_cust.cust_link_user
     *
     * @return the value of s_cust.cust_link_user
     *
     * @mbggenerated
     */
    public Integer getCustLinkUser() {
        return custLinkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_cust.cust_link_user
     *
     * @param custLinkUser the value for s_cust.cust_link_user
     *
     * @mbggenerated
     */
    public void setCustLinkUser(Integer custLinkUser) {
        this.custLinkUser = custLinkUser;
    }
}